[apis."httpbin.get"]
url = "https://httpbin.org/get"
method = "GET"
headers = {}

[apis."catfact.getFact"]
url = "https://catfact.ninja/fact"
method = "GET"
headers = {}

[apis."openai.chat"]
url = "$!OPENAI_COMPATIBLE_BASE_URL"
method = "POST"
headers = { Authorization = "Bearer $!OPENAI_COMPATIBLE_API_KEY" }
body = """
{
  "model": "$!MODEL",
  "messages": [{"role": "user", "content": "$!PROMPT"}]
}
"""

[apis."openrouter.chat"]
url = "https://openrouter.ai/api/v1/chat/completions"
method = "POST"
headers = { Authorization = "Bearer $!API_KEY" }
body = """
{
  "model": "$!MODEL",
  "messages": [{"role": "user", "content": "$OPTIONAL_PROMPT"}, {"role": "user", "content": "$!PROMPT"}]
  , "provider": {"order": ["$PROVIDER"]}
}
"""
